// <auto-generated />
namespace IndustrialAppServer.BLL.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class azureInit2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(azureInit2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812021505008_azureInit2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
